# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='distance_km',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
