# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 03:19
from __future__ import unicode_literals

from django.db import migrations
from pymongo import MongoClient


def import_from_mongo(apps, schema_editor):
    """
    Populate database with information from mongodb
    :param apps:
    :param schema_editor:
    :return:
    """
    try:
        client = MongoClient()
        col = client.tinderp.hopefuls
        mentioned_snapchat = col.find({'mentions_snapchat': True})
    except Exception as e:
        print("Unable to retrieve information from MongoDB")
        print(e)

    User = apps.get_model("tinder", "User")
    for person in mentioned_snapchat:
        # automatically save users
        User.from_mongo(person)





def undo(apps, schema_editor):
    """
    Undo migration.
    :param apps:
    :param schema_editor:
    :return:
    """
    User = apps.get_model('tinder', 'User')
    User.objects.filter(from_other=True).delete()





class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_from_mongo, undo)
    ]
