# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mentions_instagram',
            new_name='instagram_in_bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mentions_kik',
            new_name='kik_in_bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mentions_snapchat',
            new_name='snapchat_in_bio',
        ),
    ]
