# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mentions_instagram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mentions_kik',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mentions_snapchat',
        ),
    ]
