# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_auto_20161008_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data',
            new_name='_data',
        ),
    ]
