# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 03:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_auto_20161009_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), default=[], size=None),
        ),
    ]
