# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0003_auto_20161008_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tinder_id',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
