# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 03:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0003_auto_20161009_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jobs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), default=[], size=None),
        ),
    ]
