# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0003_auto_20161008_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='distance_km',
        ),
        migrations.AddField(
            model_name='user',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
