# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0004_auto_20161009_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jobs',
        ),
        migrations.AlterField(
            model_name='user',
            name='schools',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
