# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0004_auto_20161008_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
