# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0005_user_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_data',
            new_name='data',
        ),
    ]
