# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0005_auto_20161009_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schools',
            field=models.CharField(default='', max_length=200),
        ),
    ]
