# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0006_auto_20161008_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data',
        ),
    ]
