# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0007_remove_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_other',
            field=models.BooleanField(default=False),
        ),
    ]
