# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 03:19
from __future__ import unicode_literals

from django.db import migrations
from pymongo import MongoClient
from tqdm import tqdm


def import_from_mongo(apps, schema_editor):
    """
    Populate database with information from mongodb
    :param apps:
    :param schema_editor:
    :return:
    """
    try:
        client = MongoClient()
        col = client.tinderp.hopefuls
        mentioned_snapchat = col.find({'mentions_snapchat': True})
    except Exception as e:
        print("Unable to retrieve information from MongoDB")
        print(e)

    User = apps.get_model("tinder", "User")

    # map of fields between (Django User : Mongo User)
    fields = {
        'name': 'name',
        'age': 'age',
        'bio': 'bio',
        'distance': 'distance_mi',
        'instagram_username': 'instagram_username',
        'mentions_snapchat': 'mentions_snapchat',
        'mentions_kik': 'mentions_kik',
    }

    for person in tqdm(mentioned_snapchat):

        # populate kwargs from person dictionary
        kwargs = {k: person[v] for k, v in fields.items()}
        kwargs.update({
            "liked": True,
            "from_other": True,
        })

        # initialize and persist user
        user, created = User.objects.get_or_create(**kwargs)
        user._data = person
        user._photos = person.get('photos', [])
        user.save()



def undo(apps, schema_editor):
    """
    Undo migration.
    :param apps:
    :param schema_editor:
    :return:
    """
    User = apps.get_model('tinder', 'User')
    User.objects.filter(from_other=True).delete()





class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0008_user_from_other'),
    ]

    operations = [
        migrations.RunPython(import_from_mongo, undo)
    ]
