# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 04:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0009_auto_20161009_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 9, 4, 51, 22, 870459)),
        ),
    ]
