# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 04:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0010_auto_20161009_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 9, 4, 52, 36, 115165, tzinfo=utc)),
        ),
    ]
